spring:
  dubbo:
    application:
      name: demo-server
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.hikvison.ga.boot.dubbo.demo